// ADDED (AI Assistant · Slice 1): the agent's READ tool belt. Every tool takes an
// explicit userId and queries Prisma directly (no auth() / "server-only" imports),
// so the engine is testable headlessly via tsx as well as from server actions.
// All tools here are read-only and auto-run; WRITE tools (confirm-before-save)
// land in Slice 2. Results are compact JSON — token-frugal by design.
import type Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";
import {
  activeSalaryForMonth,
  recurringMonthlyIncome,
  toUiSalaryPeriod,
  toUiIncomeSource,
  normalizeTags,
} from "@/lib/expense-utils";
import type { CategoryKey, Currency } from "@/types";
import { WRITABLE_CATEGORIES, type ExpenseFields, type Proposal } from "./types";

const ALL_CATEGORIES: CategoryKey[] = [
  "food",
  "shop",
  "ent",
  "trans",
  "health",
  "bills",
  "family",
  "other",
];

const WRITABLE_CURRENCIES: Currency[] = ["SGD", "MYR", "CNY", "USD"];

// ADDED (Slice 2): WRITE tools return this instead of writing. The engine pulls the
// proposal out to render a confirm card, and feeds `modelResult` back to the model
// as the tool_result (so it knows the change is pending, not done).
export interface WriteToolOutput {
  proposal: Proposal;
  modelResult: string;
}
export function isWriteToolOutput(x: unknown): x is WriteToolOutput {
  return typeof x === "object" && x !== null && "proposal" in x && "modelResult" in x;
}

// ── helpers ──────────────────────────────────────────────────

const pad = (n: number) => String(n).padStart(2, "0");
const fmtDate = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const fmtYM = (y: number, m: number) => `${y}-${pad(m)}`;

/** Parse a YYYY-MM-DD (or YYYY-MM) string into a local Date; null if invalid. */
function parseDay(s: unknown, endOfDay = false): Date | null {
  if (typeof s !== "string") return null;
  const m = s.match(/^(\d{4})-(\d{1,2})(?:-(\d{1,2}))?$/);
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]);
  if (mo < 1 || mo > 12) return null;
  // YYYY-MM: expand to the first/last day of that month.
  const day = m[3] != null ? Number(m[3]) : endOfDay ? new Date(y, mo, 0).getDate() : 1;
  const d = endOfDay
    ? new Date(y, mo - 1, day, 23, 59, 59, 999)
    : new Date(y, mo - 1, day, 0, 0, 0, 0);
  return Number.isNaN(d.getTime()) ? null : d;
}

const toNum = (v: unknown): number | null => {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

// ── tool definitions (Anthropic tool schema) ─────────────────

export const ASSISTANT_TOOLS: Anthropic.Tool[] = [
  {
    name: "find_expenses",
    description:
      "Search the user's ENTIRE expense ledger (all time, not just recent). Use for any question about specific expenses: biggest purchases, what was bought when, spending on a merchant/keyword/tag, listing entries in a period. Returns matching rows plus the total count/amount of ALL matches (even beyond the returned limit).",
    input_schema: {
      type: "object",
      properties: {
        dateFrom: { type: "string", description: "Inclusive start date YYYY-MM-DD (or YYYY-MM for a whole month). Omit for no lower bound." },
        dateTo: { type: "string", description: "Inclusive end date YYYY-MM-DD (or YYYY-MM). Omit for no upper bound." },
        category: { type: "string", enum: ALL_CATEGORIES, description: "Filter to one spending category." },
        query: { type: "string", description: "Case-insensitive keyword matched against the note text and tags (e.g. 'grab', 'coffee', '鸡饭')." },
        minAmount: { type: "number", description: "Only expenses with amount >= this." },
        maxAmount: { type: "number", description: "Only expenses with amount <= this." },
        source: { type: "string", enum: ["manual", "voice"], description: "How the expense was logged." },
        recurringOnly: { type: "boolean", description: "true = only rows generated by recurring/fixed rules." },
        sort: {
          type: "string",
          enum: ["date_desc", "date_asc", "amount_desc"],
          description: "Row order. Use amount_desc to find the biggest expenses.",
        },
        limit: { type: "number", description: "Max rows to return (default 40, max 100)." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "find_recurring",
    description:
      "List the user's recurring/fixed expense RULES (rent, subscriptions, 家用…). A rule auto-generates one ledger expense per month across its active range. Use when the user mentions a recurring commitment, subscription, or fixed monthly cost.",
    input_schema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Case-insensitive keyword matched against the rule label/note." },
        includeInactive: { type: "boolean", description: "Also include deactivated/ended rules (default false)." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_financial_overview",
    description:
      "The user's whole financial picture right now: current salary (take-home/gross/deductions), other income streams, bonuses this year, savings goal + amount saved, monthly budget, this month's spend so far, and total recurring commitments. Call this first for any planning, affordability, or savings question.",
    input_schema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "analyze_spending",
    description:
      "Aggregate spending over a date range, grouped by category, month, or tag. Use for questions like 'what did I spend most on', 'why was March so high', month-over-month comparisons, or category breakdowns. Returns totals per group plus the recurring (fixed) portion so you can separate commitments from discretionary spend.",
    input_schema: {
      type: "object",
      properties: {
        dateFrom: { type: "string", description: "Inclusive start date YYYY-MM-DD or YYYY-MM." },
        dateTo: { type: "string", description: "Inclusive end date YYYY-MM-DD or YYYY-MM." },
        groupBy: { type: "string", enum: ["category", "month", "tag"], description: "How to group the totals." },
      },
      required: ["dateFrom", "dateTo", "groupBy"],
      additionalProperties: false,
    },
  },
  {
    name: "project_savings",
    description:
      "Estimate how long until the user reaches a savings target, from real income minus real average spend (last 3 full months). Returns saved-so-far, monthly net, months-to-target, estimated arrival month, and a category breakdown of recent spend (material for gentle what-if suggestions). Use for '多久才能存到X' / 'when can I afford X' questions.",
    input_schema: {
      type: "object",
      properties: {
        targetAmount: { type: "number", description: "The savings target. Omit to use the user's configured savings goal." },
        monthlySpendOverride: { type: "number", description: "What-if: assume this monthly spend instead of the real average (e.g. after a proposed cutback)." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_closed_months",
    description:
      "Months the user has hard-closed (locked). Expenses in a closed month cannot be changed without reopening. Mention this if the user asks about editing something in one of these months.",
    input_schema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_preferences",
    description:
      "The user's saved lifestyle/priority preferences (e.g. 'gaming brings me joy', 'travel matters more than dining'). ALWAYS check before giving spending suggestions so advice respects what they value.",
    input_schema: { type: "object", properties: {}, additionalProperties: false },
  },

  // ── WRITE tools (Slice 2) ──────────────────────────────────
  // These do NOT save anything — they PROPOSE a change that the user confirms on a
  // card in the chat. Gather precise values, call the tool, then ask the user to
  // review & confirm; never claim the change is already done.
  {
    name: "create_expense",
    description:
      "Propose ADDING one new expense to the ledger. Does NOT save — the user confirms a card in the chat first. Use when the user asks to log/add/record a spend. Provide as many details as you can infer; leave date blank for today.",
    input_schema: {
      type: "object",
      properties: {
        amount: { type: "number", description: "The amount spent (positive)." },
        category: { type: "string", enum: WRITABLE_CATEGORIES, description: "Best-fit spending category." },
        currency: { type: "string", enum: WRITABLE_CURRENCIES, description: "Currency (default SGD)." },
        note: { type: "string", description: "Short description, e.g. 'chicken rice at Maxwell'." },
        tags: { type: "array", items: { type: "string" }, description: "Optional tags, e.g. ['lunch','work']." },
        date: { type: "string", description: "Date YYYY-MM-DD. Omit for today." },
      },
      required: ["amount", "category"],
      additionalProperties: false,
    },
  },
  {
    name: "update_expense",
    description:
      "Propose EDITING an existing expense. Does NOT save — the user confirms a before→after card first. You MUST pass the expense `id` (get it from find_expenses). Only the fields you include change; you can change several at once (amount, category, currency, note, tags, date). Note: to change a RECURRING rule across months, don't use this — recurring-rule editing isn't available from chat yet.",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "number", description: "The id of the expense to edit (from find_expenses)." },
        amount: { type: "number", description: "New amount." },
        category: { type: "string", enum: WRITABLE_CATEGORIES, description: "New category." },
        currency: { type: "string", enum: WRITABLE_CURRENCIES, description: "New currency." },
        note: { type: "string", description: "New note text." },
        tags: { type: "array", items: { type: "string" }, description: "REPLACES all tags on the expense." },
        date: { type: "string", description: "New date YYYY-MM-DD." },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
  {
    name: "delete_expense",
    description:
      "Propose DELETING an existing expense. Does NOT delete — the user confirms first. You MUST pass the expense `id` (from find_expenses). If several rows could match, ask which one instead of guessing.",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "number", description: "The id of the expense to delete (from find_expenses)." },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
];

/** Names of the tools that mutate — used by the engine to route their output to a
 *  confirm card (and by the smoke script) rather than treating it as a read result. */
export const WRITE_TOOL_NAMES = new Set(["create_expense", "update_expense", "delete_expense"]);

// ── executors ────────────────────────────────────────────────

type ToolInput = Record<string, unknown>;

async function findExpenses(userId: string, input: ToolInput) {
  const where: Record<string, unknown> = { userId };

  const from = parseDay(input.dateFrom);
  const to = parseDay(input.dateTo, true);
  if (from || to) {
    where.spentAt = { ...(from && { gte: from }), ...(to && { lte: to }) };
  }
  if (typeof input.category === "string" && ALL_CATEGORIES.includes(input.category as CategoryKey)) {
    where.category = input.category;
  }
  const min = toNum(input.minAmount);
  const max = toNum(input.maxAmount);
  if (min != null || max != null) {
    where.amount = { ...(min != null && { gte: min }), ...(max != null && { lte: max }) };
  }
  if (input.source === "manual" || input.source === "voice") where.source = input.source;
  if (input.recurringOnly === true) where.fixed = true;
  if (typeof input.query === "string" && input.query.trim()) {
    const q = input.query.trim();
    where.OR = [
      { note: { contains: q, mode: "insensitive" } },
      { tags: { has: q.toLowerCase() } },
    ];
  }

  const sort = input.sort === "amount_desc"
    ? { amount: "desc" as const }
    : input.sort === "date_asc"
      ? { spentAt: "asc" as const }
      : { spentAt: "desc" as const };
  const limit = Math.min(100, Math.max(1, Math.round(toNum(input.limit) ?? 40)));

  const [rows, agg] = await Promise.all([
    prisma.expense.findMany({
      where,
      orderBy: sort,
      take: limit,
      select: {
        id: true,
        spentAt: true,
        category: true,
        amount: true,
        currency: true,
        note: true,
        tags: true,
        fixed: true,
        fixedSourceId: true,
        source: true,
      },
    }),
    prisma.expense.aggregate({ where, _count: true, _sum: { amount: true } }),
  ]);

  return {
    matchTotal: { count: agg._count, amount: Number(agg._sum.amount ?? 0) },
    returned: rows.length,
    expenses: rows.map((r) => ({
      id: r.id,
      date: fmtDate(r.spentAt),
      category: r.category,
      amount: Number(r.amount),
      currency: r.currency,
      note: r.note,
      ...(r.tags.length > 0 && { tags: r.tags }),
      ...(r.fixed && { recurring: true, ruleId: r.fixedSourceId }),
      ...(r.source === "voice" && { source: "voice" }),
    })),
  };
}

async function findRecurring(userId: string, input: ToolInput) {
  const where: Record<string, unknown> = { userId };
  if (input.includeInactive !== true) where.active = true;
  if (typeof input.query === "string" && input.query.trim()) {
    const q = input.query.trim();
    where.OR = [
      { label: { contains: q, mode: "insensitive" } },
      { note: { contains: q, mode: "insensitive" } },
    ];
  }
  const rules = await prisma.fixedExpense.findMany({ where, orderBy: { createdAt: "asc" } });
  const counts = await prisma.expense.groupBy({
    by: ["fixedSourceId"],
    where: { userId, fixedSourceId: { in: rules.map((r) => r.id) } },
    _count: true,
  });
  const countById = new Map(counts.map((c) => [c.fixedSourceId, c._count]));

  return {
    rules: rules.map((r) => ({
      ruleId: r.id,
      label: r.label,
      ...(r.note && { note: r.note }),
      category: r.category,
      amount: Number(r.amount),
      currency: r.currency,
      dueDay: r.dueDay,
      activeFrom: fmtYM(r.startYear, r.startMonth),
      activeUntil: r.endYear != null && r.endMonth != null ? fmtYM(r.endYear, r.endMonth) : "ongoing",
      active: r.active,
      generatedExpenseCount: countById.get(r.id) ?? 0,
    })),
    note:
      "Each rule generates one ledger expense per month in its range. Changing a rule updates every affected month; changing one generated expense changes only that month.",
  };
}

async function getFinancialOverview(userId: string, now: Date) {
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const monthStart = new Date(year, month - 1, 1);
  const nextMonthStart = new Date(year, month, 1);

  const [user, periods, sources, bonuses, monthAgg, fixedRules, closedCount] = await Promise.all([
    prisma.user.findUnique({ where: { id: userId } }),
    prisma.salaryPeriod.findMany({ where: { userId } }),
    prisma.incomeSource.findMany({ where: { userId } }),
    prisma.bonus.findMany({ where: { userId, year } }),
    prisma.expense.aggregate({
      _count: true,
      _sum: { amount: true },
      where: { userId, spentAt: { gte: monthStart, lt: nextMonthStart } },
    }),
    prisma.fixedExpense.findMany({ where: { userId, active: true } }),
    prisma.monthClose.count({ where: { userId } }),
  ]);
  if (!user) return { error: "user not found" };

  const active = activeSalaryForMonth(periods.map(toUiSalaryPeriod), year, month);
  const otherIncome = recurringMonthlyIncome(sources.map(toUiIncomeSource), year, month);
  const cmp = (aY: number, aM: number, bY: number, bM: number) => (aY !== bY ? aY - bY : aM - bM);
  const activeRules = fixedRules.filter((f) => {
    const started = cmp(year, month, f.startYear, f.startMonth) >= 0;
    const notEnded = f.endYear == null || f.endMonth == null || cmp(year, month, f.endYear, f.endMonth) <= 0;
    return started && notEnded;
  });
  const spent = Number(monthAgg._sum.amount ?? 0);
  const budget = Number(user.monthlyBudget);

  return {
    today: fmtDate(now),
    displayCurrency: user.currency,
    income: {
      monthlyTakeHomeSalary: active?.monthlySalary ?? 0,
      grossSalary: active?.grossSalary ?? 0,
      deductions: active?.deductions ?? 0,
      otherRecurringMonthlyIncome: otherIncome,
      totalMonthlyIncome: (active?.monthlySalary ?? 0) + otherIncome,
      payDay: user.payDay,
      payFrequency: user.payFrequency,
      bonusesThisYear: bonuses.map((b) => ({ month: b.month, amount: Number(b.amount), label: b.label })),
    },
    savings: {
      goal: Number(user.savingsGoal),
      saved: Number(user.saved),
      remainingToGoal: Math.max(0, Number(user.savingsGoal) - Number(user.saved)),
    },
    thisMonth: {
      month: fmtYM(year, month),
      spentSoFar: spent,
      expenseCount: monthAgg._count,
      monthlyBudget: budget,
      budgetRemaining: budget > 0 ? budget - spent : null,
    },
    recurringCommitments: {
      activeRuleCount: activeRules.length,
      totalMonthlyAmount: activeRules.reduce((a, f) => a + Number(f.amount), 0),
    },
    closedMonthCount: closedCount,
  };
}

async function analyzeSpending(userId: string, input: ToolInput) {
  const from = parseDay(input.dateFrom);
  const to = parseDay(input.dateTo, true);
  if (!from || !to) return { error: "dateFrom and dateTo must be YYYY-MM-DD or YYYY-MM" };
  if (to.getTime() - from.getTime() > 3 * 366 * 24 * 3600 * 1000) {
    return { error: "range too large — max 3 years per call" };
  }
  const groupBy = input.groupBy === "month" || input.groupBy === "tag" ? input.groupBy : "category";

  const rows = await prisma.expense.findMany({
    where: { userId, spentAt: { gte: from, lte: to } },
    select: { spentAt: true, amount: true, category: true, tags: true, fixed: true },
  });

  const groups = new Map<string, { total: number; count: number; recurring: number }>();
  let total = 0;
  let recurringTotal = 0;
  for (const r of rows) {
    const amt = Number(r.amount);
    total += amt;
    if (r.fixed) recurringTotal += amt;
    const keys =
      groupBy === "category"
        ? [r.category as string]
        : groupBy === "month"
          ? [fmtYM(r.spentAt.getFullYear(), r.spentAt.getMonth() + 1)]
          : r.tags.length > 0
            ? r.tags
            : ["(untagged)"];
    for (const k of keys) {
      const g = groups.get(k) ?? { total: 0, count: 0, recurring: 0 };
      g.total += amt;
      g.count += 1;
      if (r.fixed) g.recurring += amt;
      groups.set(k, g);
    }
  }

  return {
    range: { from: fmtDate(from), to: fmtDate(to) },
    overall: { total, expenseCount: rows.length, recurringPortion: recurringTotal, discretionaryPortion: total - recurringTotal },
    groupedBy: groupBy,
    groups: [...groups.entries()]
      .sort((a, b) => b[1].total - a[1].total)
      .slice(0, 40)
      .map(([key, g]) => ({ [groupBy]: key, total: g.total, count: g.count, recurringPortion: g.recurring })),
    ...(groupBy === "tag" && { note: "an expense can carry several tags, so tag totals may overlap" }),
  };
}

async function projectSavings(userId: string, input: ToolInput, now: Date) {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) return { error: "user not found" };

  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const target = toNum(input.targetAmount) ?? Number(user.savingsGoal);
  const saved = Number(user.saved);

  const [periods, sources] = await Promise.all([
    prisma.salaryPeriod.findMany({ where: { userId } }),
    prisma.incomeSource.findMany({ where: { userId } }),
  ]);
  const salary = activeSalaryForMonth(periods.map(toUiSalaryPeriod), year, month)?.monthlySalary ?? 0;
  const otherIncome = recurringMonthlyIncome(sources.map(toUiIncomeSource), year, month);
  const monthlyIncome = salary + otherIncome;

  // Average spend over the last 3 FULL calendar months (falls back to whatever
  // history exists; a brand-new user gets the current month so far).
  const windowStart = new Date(year, month - 4, 1);
  const windowEnd = new Date(year, month - 1, 1);
  const past = await prisma.expense.findMany({
    where: { userId, spentAt: { gte: windowStart, lt: windowEnd } },
    select: { spentAt: true, amount: true, category: true },
  });
  let avgSpend: number;
  let windowLabel: string;
  let byCategory: { category: string; monthlyAverage: number }[] = [];
  if (past.length > 0) {
    const monthsSeen = new Set(past.map((r) => `${r.spentAt.getFullYear()}-${r.spentAt.getMonth()}`)).size;
    const div = Math.max(1, monthsSeen);
    avgSpend = past.reduce((a, r) => a + Number(r.amount), 0) / div;
    windowLabel = `average of last ${div} full month(s)`;
    const catTotals = new Map<string, number>();
    for (const r of past) catTotals.set(r.category, (catTotals.get(r.category) ?? 0) + Number(r.amount));
    byCategory = [...catTotals.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([category, t]) => ({ category, monthlyAverage: Math.round((t / div) * 100) / 100 }));
  } else {
    const cur = await prisma.expense.aggregate({
      _sum: { amount: true },
      where: { userId, spentAt: { gte: new Date(year, month - 1, 1) } },
    });
    avgSpend = Number(cur._sum.amount ?? 0);
    windowLabel = "current month so far (no full-month history yet)";
  }

  const assumedSpend = toNum(input.monthlySpendOverride) ?? avgSpend;
  const monthlyNet = monthlyIncome - assumedSpend;
  const remaining = Math.max(0, target - saved);
  const monthsToTarget = remaining === 0 ? 0 : monthlyNet > 0 ? Math.ceil(remaining / monthlyNet) : null;
  let estimatedArrival: string | null = null;
  if (monthsToTarget != null) {
    const d = new Date(year, month - 1 + monthsToTarget, 1);
    estimatedArrival = fmtYM(d.getFullYear(), d.getMonth() + 1);
  }

  return {
    target,
    saved,
    remainingToTarget: remaining,
    monthlyIncome: { salary, otherRecurring: otherIncome, total: monthlyIncome },
    monthlySpend: {
      basis: toNum(input.monthlySpendOverride) != null ? "override (what-if)" : windowLabel,
      amount: Math.round(assumedSpend * 100) / 100,
    },
    monthlyNetSavings: Math.round(monthlyNet * 100) / 100,
    monthsToTarget,
    estimatedArrival,
    ...(monthsToTarget == null && remaining > 0 && {
      note: "monthly spend meets or exceeds income at this rate — the target is unreachable without changes",
    }),
    recentSpendByCategory: byCategory,
  };
}

async function getClosedMonths(userId: string) {
  const rows = await prisma.monthClose.findMany({
    where: { userId },
    orderBy: [{ year: "desc" }, { month: "desc" }],
  });
  return { closedMonths: rows.map((r) => fmtYM(r.year, r.month)) };
}

async function getPreferences(userId: string) {
  const rows = await prisma.userPreference.findMany({ where: { userId } });
  return {
    preferences: rows.map((r) => ({ key: r.key, value: r.value })),
    ...(rows.length === 0 && { note: "no saved preferences yet — avoid assuming what the user values" }),
  };
}

// ── write proposals (Slice 2) ────────────────────────────────
// Each builds a self-contained Proposal (no DB writes). The engine assigns the
// real proposal.id (the tool_use block id) after these return.

const CURRENCY_SYMBOL: Record<Currency, string> = { SGD: "S$", MYR: "RM", CNY: "¥", USD: "$" };
const fmtMoney = (amount: number, currency: Currency) =>
  `${CURRENCY_SYMBOL[currency] ?? ""}${amount.toFixed(2)}`;

/** "YYYY-MM" if that calendar month is hard-closed for the user, else null. */
async function closedMonthKey(userId: string, d: Date): Promise<string | null> {
  const year = d.getFullYear();
  const month = d.getMonth() + 1;
  const row = await prisma.monthClose.findUnique({
    where: { userId_year_month: { userId, year, month } },
  });
  return row ? fmtYM(year, month) : null;
}

/** Parse an agent-supplied YYYY-MM-DD to local noon (avoids day-boundary TZ drift). */
function parseSpendDate(s: unknown): Date | null {
  const d = parseDay(s);
  if (!d) return null;
  d.setHours(12, 0, 0, 0);
  return d;
}

function pickCategory(v: unknown): CategoryKey | null {
  return typeof v === "string" && WRITABLE_CATEGORIES.includes(v as CategoryKey)
    ? (v as CategoryKey)
    : null;
}
function pickCurrency(v: unknown): Currency | null {
  return typeof v === "string" && WRITABLE_CURRENCIES.includes(v as Currency) ? (v as Currency) : null;
}

/** A shared "not a proposal" shape so Claude can recover (ask again / re-search). */
type ToolError = { error: string };

async function proposeCreateExpense(
  userId: string,
  input: ToolInput,
  now: Date,
): Promise<WriteToolOutput | ToolError> {
  const amount = toNum(input.amount);
  if (amount == null || amount <= 0) return { error: "amount must be a positive number" };
  const category = pickCategory(input.category);
  if (!category) return { error: `category must be one of: ${WRITABLE_CATEGORIES.join(", ")}` };
  const currency = pickCurrency(input.currency) ?? "SGD";

  let when = now;
  if (input.date != null) {
    const parsed = parseSpendDate(input.date);
    if (!parsed) return { error: "date must be YYYY-MM-DD" };
    when = parsed;
  }
  const tags = normalizeTags(Array.isArray(input.tags) ? (input.tags as string[]) : []);
  const note = typeof input.note === "string" ? input.note.trim() : "";
  const fields: ExpenseFields = { amount, currency, category, note, tags, spentAt: when.toISOString() };
  const closedMonth = await closedMonthKey(userId, when);

  return {
    proposal: {
      id: "",
      kind: "create_expense",
      summary: `Add ${fmtMoney(amount, currency)} · ${category}${note ? ` · ${note}` : ""}`,
      closedMonth,
      create: fields,
    },
    modelResult:
      "Add-expense proposal is on screen as a confirmation card — nothing is saved yet. " +
      "Briefly ask the user to review and Confirm it (don't restate every field)." +
      (closedMonth ? ` Note: ${closedMonth} is closed; the card lets them add anyway or cancel.` : ""),
  };
}

/** Build ExpenseFields from a DB row. */
function rowToFields(r: {
  amount: unknown;
  currency: string;
  category: string;
  note: string | null;
  tags: string[];
  spentAt: Date;
}): ExpenseFields {
  return {
    amount: Number(r.amount),
    currency: r.currency as Currency,
    category: r.category as CategoryKey,
    note: r.note ?? "",
    tags: r.tags,
    spentAt: r.spentAt.toISOString(),
  };
}

async function proposeUpdateExpense(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const id = toNum(input.id);
  if (id == null || !Number.isInteger(id)) {
    return { error: "pass the numeric id of the expense (from find_expenses)" };
  }
  const row = await prisma.expense.findFirst({
    where: { id, userId },
    select: {
      id: true, amount: true, currency: true, category: true,
      note: true, tags: true, spentAt: true, fixed: true, fixedSourceId: true,
    },
  });
  if (!row) return { error: "no expense with that id — call find_expenses to get the right id" };

  const before = rowToFields(row);
  const after: ExpenseFields = { ...before };
  let changed = false;

  if (input.amount !== undefined) {
    const a = toNum(input.amount);
    if (a == null || a <= 0) return { error: "amount must be a positive number" };
    after.amount = a; changed = true;
  }
  if (input.category !== undefined) {
    const c = pickCategory(input.category);
    if (!c) return { error: `category must be one of: ${WRITABLE_CATEGORIES.join(", ")}` };
    after.category = c; changed = true;
  }
  if (input.currency !== undefined) {
    const cur = pickCurrency(input.currency);
    if (!cur) return { error: `currency must be one of: ${WRITABLE_CURRENCIES.join(", ")}` };
    after.currency = cur; changed = true;
  }
  if (input.note !== undefined) {
    after.note = typeof input.note === "string" ? input.note.trim() : "";
    changed = true;
  }
  if (input.tags !== undefined) {
    after.tags = normalizeTags(Array.isArray(input.tags) ? (input.tags as string[]) : []);
    changed = true;
  }
  if (input.date !== undefined) {
    const parsed = parseSpendDate(input.date);
    if (!parsed) return { error: "date must be YYYY-MM-DD" };
    after.spentAt = parsed.toISOString();
    changed = true;
  }
  if (!changed) return { error: "no changes given — say what to change (amount, category, note, tags, date…)" };

  // Either the row's current month or (if the date moves) the target month being
  // closed will block the edit — surface whichever is closed so the card can warn.
  const curClosed = await closedMonthKey(userId, new Date(before.spentAt!));
  const newClosed =
    after.spentAt !== before.spentAt ? await closedMonthKey(userId, new Date(after.spentAt!)) : null;
  const closedMonth = curClosed ?? newClosed;
  const recurringWarning = row.fixed || row.fixedSourceId != null;

  return {
    proposal: {
      id: "",
      kind: "update_expense",
      summary: `Update ${fmtMoney(before.amount, before.currency)} · ${before.category}`,
      closedMonth,
      recurringWarning,
      expenseId: row.id,
      before,
      after,
    },
    modelResult:
      "Edit proposal (before→after) is on screen as a confirmation card — nothing is saved yet. " +
      "Ask the user to review and Confirm." +
      (recurringWarning
        ? " Heads-up: this row was generated by a recurring rule, so confirming changes ONLY this month (the rule stays as-is; recurring-rule editing from chat is coming soon)."
        : "") +
      (closedMonth ? ` Note: ${closedMonth} is closed; the card lets them edit anyway or cancel.` : ""),
  };
}

async function proposeDeleteExpense(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const id = toNum(input.id);
  if (id == null || !Number.isInteger(id)) {
    return { error: "pass the numeric id of the expense (from find_expenses)" };
  }
  const row = await prisma.expense.findFirst({
    where: { id, userId },
    select: {
      id: true, amount: true, currency: true, category: true,
      note: true, tags: true, spentAt: true, fixed: true, fixedSourceId: true,
    },
  });
  if (!row) return { error: "no expense with that id — call find_expenses to get the right id" };

  const target = rowToFields(row);
  const closedMonth = await closedMonthKey(userId, row.spentAt);
  const recurringWarning = row.fixed || row.fixedSourceId != null;

  return {
    proposal: {
      id: "",
      kind: "delete_expense",
      summary: `Delete ${fmtMoney(target.amount, target.currency)} · ${target.category}${target.note ? ` · ${target.note}` : ""}`,
      closedMonth,
      recurringWarning,
      expenseId: row.id,
      target,
    },
    modelResult: closedMonth
      ? `That expense is in a closed month (${closedMonth}); it can't be deleted until the month is reopened on the Ledger page. Tell the user gently.`
      : "Delete proposal is on screen as a confirmation card — nothing is deleted yet. Ask the user to confirm." +
        (recurringWarning
          ? " Note: this row came from a recurring rule; deleting it removes only this month's entry."
          : ""),
  };
}

/** Run one tool by name; the engine wraps this per tool_use block. */
export async function executeAssistantTool(
  userId: string,
  name: string,
  input: ToolInput,
  now: Date = new Date(),
): Promise<unknown> {
  switch (name) {
    case "find_expenses":
      return findExpenses(userId, input);
    case "find_recurring":
      return findRecurring(userId, input);
    case "get_financial_overview":
      return getFinancialOverview(userId, now);
    case "analyze_spending":
      return analyzeSpending(userId, input);
    case "project_savings":
      return projectSavings(userId, input, now);
    case "get_closed_months":
      return getClosedMonths(userId);
    case "get_preferences":
      return getPreferences(userId);
    // WRITE tools (Slice 2) — return a proposal (no DB write); engine → confirm card.
    case "create_expense":
      return proposeCreateExpense(userId, input, now);
    case "update_expense":
      return proposeUpdateExpense(userId, input);
    case "delete_expense":
      return proposeDeleteExpense(userId, input);
    default:
      return { error: `unknown tool: ${name}` };
  }
}
