// ADDED (AI Assistant · Slice 1): the agent's READ tool belt. Every tool takes an
// explicit userId and queries Prisma directly (no auth() / "server-only" imports),
// so the engine is testable headlessly via tsx as well as from server actions.
// All tools here are read-only and auto-run; WRITE tools (confirm-before-save)
// land in Slice 2. Results are compact JSON — token-frugal by design.
import type Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";
import {
  activeSalaryForMonth,
  recurringMonthlyIncome,
  toUiSalaryPeriod,
  toUiIncomeSource,
  normalizeTags,
  closedMonthsInRange,
} from "@/lib/expense-utils";
import type { CategoryKey, Currency } from "@/types";
import {
  WRITABLE_CATEGORIES,
  type ExpenseFields,
  type Proposal,
  type RecurringSnapshot,
  type RecurringChanges,
  type RecurringCreateFields,
  type SavingsSettingsFields,
  type SalaryFields,
  type BonusFields,
} from "./types";

// Exported: create_recurring allows "family" (家用/family support), unlike plain
// expense create/update which is restricted to WRITABLE_CATEGORIES.
export const ALL_CATEGORIES: CategoryKey[] = [
  "food",
  "shop",
  "ent",
  "trans",
  "health",
  "bills",
  "family",
  "other",
];

const WRITABLE_CURRENCIES: Currency[] = ["SGD", "MYR", "CNY", "USD"];

// ADDED (Slice 2): WRITE tools return this instead of writing. The engine pulls the
// proposal out to render a confirm card, and feeds `modelResult` back to the model
// as the tool_result (so it knows the change is pending, not done).
export interface WriteToolOutput {
  proposal: Proposal;
  modelResult: string;
}
export function isWriteToolOutput(x: unknown): x is WriteToolOutput {
  return typeof x === "object" && x !== null && "proposal" in x && "modelResult" in x;
}

// ── helpers ──────────────────────────────────────────────────

const pad = (n: number) => String(n).padStart(2, "0");
const fmtDate = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const fmtYM = (y: number, m: number) => `${y}-${pad(m)}`;

/** Parse a YYYY-MM-DD (or YYYY-MM) string into a local Date; null if invalid. */
function parseDay(s: unknown, endOfDay = false): Date | null {
  if (typeof s !== "string") return null;
  const m = s.match(/^(\d{4})-(\d{1,2})(?:-(\d{1,2}))?$/);
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]);
  if (mo < 1 || mo > 12) return null;
  // YYYY-MM: expand to the first/last day of that month.
  const day = m[3] != null ? Number(m[3]) : endOfDay ? new Date(y, mo, 0).getDate() : 1;
  const d = endOfDay
    ? new Date(y, mo - 1, day, 23, 59, 59, 999)
    : new Date(y, mo - 1, day, 0, 0, 0, 0);
  return Number.isNaN(d.getTime()) ? null : d;
}

const toNum = (v: unknown): number | null => {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

// ── tool definitions (Anthropic tool schema) ─────────────────

export const ASSISTANT_TOOLS: Anthropic.Tool[] = [
  {
    name: "find_expenses",
    description:
      "Search the user's ENTIRE expense ledger (all time, not just recent). Use for any question about specific expenses: biggest purchases, what was bought when, spending on a merchant/keyword/tag, listing entries in a period. Returns matching rows plus the total count/amount of ALL matches (even beyond the returned limit).",
    input_schema: {
      type: "object",
      properties: {
        dateFrom: { type: "string", description: "Inclusive start date YYYY-MM-DD (or YYYY-MM for a whole month). Omit for no lower bound." },
        dateTo: { type: "string", description: "Inclusive end date YYYY-MM-DD (or YYYY-MM). Omit for no upper bound." },
        category: { type: "string", enum: ALL_CATEGORIES, description: "Filter to one spending category." },
        query: { type: "string", description: "Case-insensitive keyword matched against the note text and tags (e.g. 'grab', 'coffee', '鸡饭')." },
        minAmount: { type: "number", description: "Only expenses with amount >= this." },
        maxAmount: { type: "number", description: "Only expenses with amount <= this." },
        source: { type: "string", enum: ["manual", "voice"], description: "How the expense was logged." },
        recurringOnly: { type: "boolean", description: "true = only rows generated by recurring/fixed rules." },
        sort: {
          type: "string",
          enum: ["date_desc", "date_asc", "amount_desc"],
          description: "Row order. Use amount_desc to find the biggest expenses.",
        },
        limit: { type: "number", description: "Max rows to return (default 40, max 100)." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "find_recurring",
    description:
      "List the user's recurring/fixed expense RULES (rent, subscriptions, 家用…). A rule auto-generates one ledger expense per month across its active range. Use when the user mentions a recurring commitment, subscription, or fixed monthly cost.",
    input_schema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Case-insensitive keyword matched against the rule label/note." },
        includeInactive: { type: "boolean", description: "Also include deactivated/ended rules (default false)." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_financial_overview",
    description:
      "The user's whole financial picture right now: current salary (take-home/gross/deductions), other income streams, bonuses this year, savings goal + amount saved, monthly budget, this month's spend so far, and total recurring commitments. Call this first for any planning, affordability, or savings question.",
    input_schema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "analyze_spending",
    description:
      "Aggregate spending over a date range, grouped by category, month, or tag. Use for questions like 'what did I spend most on', 'why was March so high', month-over-month comparisons, or category breakdowns. Returns totals per group plus the recurring (fixed) portion so you can separate commitments from discretionary spend.",
    input_schema: {
      type: "object",
      properties: {
        dateFrom: { type: "string", description: "Inclusive start date YYYY-MM-DD or YYYY-MM." },
        dateTo: { type: "string", description: "Inclusive end date YYYY-MM-DD or YYYY-MM." },
        groupBy: { type: "string", enum: ["category", "month", "tag"], description: "How to group the totals." },
      },
      required: ["dateFrom", "dateTo", "groupBy"],
      additionalProperties: false,
    },
  },
  {
    name: "project_savings",
    description:
      "Estimate how long until the user reaches a savings target, from real income minus real average spend (last 3 full months). Returns saved-so-far, monthly net, months-to-target, estimated arrival month, and a category breakdown of recent spend (material for gentle what-if suggestions). Use for '多久才能存到X' / 'when can I afford X' questions.",
    input_schema: {
      type: "object",
      properties: {
        targetAmount: { type: "number", description: "The savings target. Omit to use the user's configured savings goal." },
        monthlySpendOverride: { type: "number", description: "What-if: assume this monthly spend instead of the real average (e.g. after a proposed cutback)." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_closed_months",
    description:
      "Months the user has hard-closed (locked). Expenses in a closed month cannot be changed without reopening. Mention this if the user asks about editing something in one of these months.",
    input_schema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_preferences",
    description:
      "The user's saved lifestyle/priority preferences (e.g. 'gaming brings me joy', 'travel matters more than dining'). ALWAYS check before giving spending suggestions so advice respects what they value.",
    input_schema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "find_bonuses",
    description:
      "List the user's recorded bonuses (year-scoped one-off income on top of salary). Call this to get a bonus's id before update_bonus / delete_bonus, or to answer questions about bonuses.",
    input_schema: {
      type: "object",
      properties: {
        year: { type: "number", description: "Only bonuses in this year (e.g. 2026). Omit for all years." },
      },
      additionalProperties: false,
    },
  },

  // ── WRITE tools (Slice 2) ──────────────────────────────────
  // These do NOT save anything — they PROPOSE a change that the user confirms on a
  // card in the chat. Gather precise values, call the tool, then ask the user to
  // review & confirm; never claim the change is already done.
  {
    name: "create_expense",
    description:
      "Propose ADDING one new expense to the ledger. Does NOT save — the user confirms a card in the chat first. Use when the user asks to log/add/record a spend. Provide as many details as you can infer; leave date blank for today.",
    input_schema: {
      type: "object",
      properties: {
        amount: { type: "number", description: "The amount spent (positive)." },
        category: { type: "string", enum: WRITABLE_CATEGORIES, description: "Best-fit spending category." },
        currency: { type: "string", enum: WRITABLE_CURRENCIES, description: "Currency (default SGD)." },
        note: { type: "string", description: "Short description, e.g. 'chicken rice at Maxwell'." },
        tags: { type: "array", items: { type: "string" }, description: "Optional tags, e.g. ['lunch','work']." },
        date: { type: "string", description: "Date YYYY-MM-DD. Omit for today." },
      },
      required: ["amount", "category"],
      additionalProperties: false,
    },
  },
  {
    name: "update_expense",
    description:
      "Propose EDITING an existing expense. Does NOT save — the user confirms a before→after card first. You MUST pass the expense `id` (get it from find_expenses). Only the fields you include change; you can change several at once (amount, category, currency, note, tags, date). Note: to change a RECURRING rule across months, don't use this — recurring-rule editing isn't available from chat yet.",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "number", description: "The id of the expense to edit (from find_expenses)." },
        amount: { type: "number", description: "New amount." },
        category: { type: "string", enum: WRITABLE_CATEGORIES, description: "New category." },
        currency: { type: "string", enum: WRITABLE_CURRENCIES, description: "New currency." },
        note: { type: "string", description: "New note text." },
        tags: { type: "array", items: { type: "string" }, description: "REPLACES all tags on the expense." },
        date: { type: "string", description: "New date YYYY-MM-DD." },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
  {
    name: "delete_expense",
    description:
      "Propose DELETING an existing expense. Does NOT delete — the user confirms first. You MUST pass the expense `id` (from find_expenses). If several rows could match, ask which one instead of guessing.",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "number", description: "The id of the expense to delete (from find_expenses)." },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
  {
    name: "create_recurring",
    description:
      "Propose setting up a brand-NEW recurring/fixed monthly commitment (rent, subscription, family support/家用…) — NOT for editing an existing one (use edit_recurring for that). Does NOT save — the user confirms a card first. Creates a RULE that auto-generates one real expense per month going forward, and retroactively materializes any already-due months back to the start month (skipping any that are hard-closed). Consider calling find_recurring first if a similar rule might already exist, to avoid a duplicate.",
    input_schema: {
      type: "object",
      properties: {
        label: { type: "string", description: "Short name, e.g. 'Rent', 'Netflix', 'Family support'." },
        amount: { type: "number", description: "Monthly amount (positive)." },
        category: {
          type: "string",
          enum: ALL_CATEGORIES,
          description: "Best-fit category — recurring items MAY use 'family' (unlike plain expenses).",
        },
        currency: { type: "string", enum: WRITABLE_CURRENCIES, description: "Currency (default SGD)." },
        note: { type: "string", description: "Optional short detail." },
        dueDay: { type: "number", description: "Day of month it's due, 1–31 (default 1)." },
        startMonth: { type: "string", description: "First month it applies, YYYY-MM. Defaults to the current month." },
        endMonth: { type: "string", description: "Last month it applies, YYYY-MM. Omit for ongoing." },
      },
      required: ["label", "amount", "category"],
      additionalProperties: false,
    },
  },
  {
    name: "edit_recurring",
    description:
      "Propose editing a RECURRING RULE (rent, subscription, 家用…) — the smart way to change a repeating commitment so EVERY affected month, the ledger, calendar, dashboard and income all move together (NOT one stray generated row; for that use update_expense). Does NOT save — the user confirms a card first. Get `ruleId` from find_recurring. Choose the mode:\n" +
      "• mode='rate_change' — the amount changed FROM a point in time (a raise/cut). Earlier months keep their old amount; the new amount applies from `fromMonth` onward. Use for 'rent went up to 1300 from May', 'my Netflix is 19 now'. Provide `newAmount` (+ optional `fromMonth`, default = this month).\n" +
      "• mode='redefine' — rewrite the rule's definition and re-apply it to EVERY month it covers (past included). Use when the user means 'it has always been / make it X across the board', or to fix the label/category/currency/note/due-day. Provide the fields to change.\n" +
      "If it's unclear whether the user wants rate_change (from now on, keep history) or redefine (all months), ASK before calling. To change the rule's active START/END months, use the manual editor instead (mention the card's Edit button or the Recurring page).",
    input_schema: {
      type: "object",
      properties: {
        ruleId: { type: "number", description: "The recurring rule's id (from find_recurring)." },
        mode: {
          type: "string",
          enum: ["rate_change", "redefine"],
          description: "rate_change = amount changes from a month onward (keep earlier); redefine = rewrite the whole rule.",
        },
        newAmount: { type: "number", description: "rate_change: the new monthly amount (positive)." },
        fromMonth: { type: "string", description: "rate_change: month the new amount starts, YYYY-MM. Omit for the current month." },
        amount: { type: "number", description: "redefine: new amount applied to every month." },
        label: { type: "string", description: "redefine: new name for the rule." },
        note: { type: "string", description: "redefine: new note/detail (pass empty string to clear)." },
        category: { type: "string", enum: WRITABLE_CATEGORIES, description: "redefine: new category." },
        currency: { type: "string", enum: WRITABLE_CURRENCIES, description: "redefine: new currency." },
        dueDay: { type: "number", description: "redefine: new due day of month (1–31)." },
      },
      required: ["ruleId", "mode"],
      additionalProperties: false,
    },
  },
  {
    name: "set_preference",
    description:
      "Propose remembering a lifestyle/spending PREFERENCE the user tells you (e.g. 'gaming brings me joy — don't nag', 'travel matters more than dining', 'trying to cut coffee'). Does NOT save — the user confirms first. Stored so future suggestions respect what they value (read back via get_preferences). Use a short, stable `key` (e.g. 'gaming', 'dining', 'priorities') and a natural-language `value`.",
    input_schema: {
      type: "object",
      properties: {
        key: { type: "string", description: "A short, stable topic key, e.g. 'gaming' or 'priorities'." },
        value: { type: "string", description: "What to remember, in the user's words." },
      },
      required: ["key", "value"],
      additionalProperties: false,
    },
  },
  {
    name: "set_month_status",
    description:
      "Propose REOPENING or CLOSING a month's books. Closing a month LOCKS every expense in it (no add/edit/delete until reopened); reopening UNLOCKS it. Does NOT change anything — the user confirms a card first. Use when the user asks to reopen/close a month, or offer it when an edit/delete is blocked because the month is closed. Pass month as YYYY-MM.",
    input_schema: {
      type: "object",
      properties: {
        month: { type: "string", description: "The month to change, YYYY-MM (e.g. 2026-06)." },
        action: { type: "string", enum: ["reopen", "close"], description: "reopen = unlock the month; close = lock it." },
      },
      required: ["month", "action"],
      additionalProperties: false,
    },
  },

  // ── income-management WRITE tools (Slice 2d) ───────────────
  // The write counterparts to get_financial_overview. Each PROPOSES a change (confirm
  // card); nothing is saved until the user taps Confirm. On confirm they route to the
  // SAME server actions the Income page uses, so the year rollup + dashboard move.
  {
    name: "set_savings_goal",
    description:
      "Propose changing the user's savings GOAL, amount SAVED so far, monthly BUDGET, pay DAY, or pay FREQUENCY. Does NOT save — the user confirms a before→after card first. Pass ONLY the fields they want to change. Use for '把存钱目标改成10万', 'set my monthly budget to 2000', 'I've saved 50k now', 'my pay day is the 28th'.",
    input_schema: {
      type: "object",
      properties: {
        savingsGoal: { type: "number", description: "Target amount to save (>= 0)." },
        saved: { type: "number", description: "Amount saved so far (>= 0)." },
        monthlyBudget: { type: "number", description: "Monthly spending budget (>= 0) — powers the dashboard spend ring." },
        payDay: { type: "number", description: "Day of month salary lands, 1–31." },
        payFrequency: { type: "string", description: "e.g. 'Monthly', 'Bi-weekly', 'Weekly'." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "adjust_salary",
    description:
      "Propose setting the user's monthly TAKE-HOME salary, effective from a month. Does NOT save — the user confirms a card first. Routes to the salary timeline: the SAME effective month CORRECTS that period; a LATER month is a RAISE/cut that keeps earlier months at their old salary. Use for '调整salary到3500', 'got a raise to 5000 from July', 'my take-home is 4200 now'. If it's unclear whether they're correcting a mistake vs logging a raise (which changes the effective month), ASK. Gross salary + CPF/deductions are OPTIONAL refinements — if the user only gives take-home, that's enough; don't force asking.",
    input_schema: {
      type: "object",
      properties: {
        monthlySalary: { type: "number", description: "Take-home pay per month (positive)." },
        effectiveMonth: { type: "string", description: "Month it takes effect, YYYY-MM. Omit for the current month." },
        grossSalary: { type: "number", description: "Optional gross (pre-deduction) monthly salary." },
        deductions: { type: "number", description: "Optional CPF / other monthly deductions." },
        label: { type: "string", description: "Optional note, e.g. 'Raise', 'Promotion'." },
      },
      required: ["monthlySalary"],
      additionalProperties: false,
    },
  },
  {
    name: "create_bonus",
    description:
      "Propose adding a BONUS — a one-off amount on top of salary, filed to a specific year + month. Does NOT save — the user confirms a card first. Use for 'add my 5000 year-end bonus', '三月发了3000奖金'.",
    input_schema: {
      type: "object",
      properties: {
        amount: { type: "number", description: "Bonus amount (positive)." },
        label: { type: "string", description: "Short name, e.g. 'Year-end bonus', 'Q2 bonus'." },
        month: { type: "number", description: "Month 1–12 it was/will be received. Omit for the current month." },
        year: { type: "number", description: "Year it belongs to. Omit for the current year." },
      },
      required: ["amount"],
      additionalProperties: false,
    },
  },
  {
    name: "update_bonus",
    description:
      "Propose editing an existing BONUS. Does NOT save — the user confirms a before→after card first. You MUST pass the bonus `id` (from find_bonuses). Only the fields you include change (amount, label, month, year).",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "number", description: "The bonus id (from find_bonuses)." },
        amount: { type: "number", description: "New amount." },
        label: { type: "string", description: "New label." },
        month: { type: "number", description: "New month, 1–12." },
        year: { type: "number", description: "New year." },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
  {
    name: "delete_bonus",
    description:
      "Propose DELETING a bonus. Does NOT delete — the user confirms first. You MUST pass the bonus `id` (from find_bonuses). If several could match, ask which one instead of guessing.",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "number", description: "The bonus id (from find_bonuses)." },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
];

/** Names of the tools that mutate — used by the engine to route their output to a
 *  confirm card (and by the smoke script) rather than treating it as a read result. */
export const WRITE_TOOL_NAMES = new Set([
  "create_expense",
  "update_expense",
  "delete_expense",
  "create_recurring",
  "edit_recurring",
  "set_preference",
  "set_month_status",
  // income management (Slice 2d)
  "set_savings_goal",
  "adjust_salary",
  "create_bonus",
  "update_bonus",
  "delete_bonus",
]);

// ── executors ────────────────────────────────────────────────

type ToolInput = Record<string, unknown>;

async function findExpenses(userId: string, input: ToolInput) {
  const where: Record<string, unknown> = { userId };

  const from = parseDay(input.dateFrom);
  const to = parseDay(input.dateTo, true);
  if (from || to) {
    where.spentAt = { ...(from && { gte: from }), ...(to && { lte: to }) };
  }
  if (typeof input.category === "string" && ALL_CATEGORIES.includes(input.category as CategoryKey)) {
    where.category = input.category;
  }
  const min = toNum(input.minAmount);
  const max = toNum(input.maxAmount);
  if (min != null || max != null) {
    where.amount = { ...(min != null && { gte: min }), ...(max != null && { lte: max }) };
  }
  if (input.source === "manual" || input.source === "voice") where.source = input.source;
  if (input.recurringOnly === true) where.fixed = true;
  if (typeof input.query === "string" && input.query.trim()) {
    const q = input.query.trim();
    where.OR = [
      { note: { contains: q, mode: "insensitive" } },
      { tags: { has: q.toLowerCase() } },
    ];
  }

  const sort = input.sort === "amount_desc"
    ? { amount: "desc" as const }
    : input.sort === "date_asc"
      ? { spentAt: "asc" as const }
      : { spentAt: "desc" as const };
  const limit = Math.min(100, Math.max(1, Math.round(toNum(input.limit) ?? 40)));

  const [rows, agg] = await Promise.all([
    prisma.expense.findMany({
      where,
      orderBy: sort,
      take: limit,
      select: {
        id: true,
        spentAt: true,
        category: true,
        amount: true,
        currency: true,
        note: true,
        tags: true,
        fixed: true,
        fixedSourceId: true,
        source: true,
      },
    }),
    prisma.expense.aggregate({ where, _count: true, _sum: { amount: true } }),
  ]);

  return {
    matchTotal: { count: agg._count, amount: Number(agg._sum.amount ?? 0) },
    returned: rows.length,
    expenses: rows.map((r) => ({
      id: r.id,
      date: fmtDate(r.spentAt),
      category: r.category,
      amount: Number(r.amount),
      currency: r.currency,
      note: r.note,
      ...(r.tags.length > 0 && { tags: r.tags }),
      ...(r.fixed && { recurring: true, ruleId: r.fixedSourceId }),
      ...(r.source === "voice" && { source: "voice" }),
    })),
  };
}

async function findRecurring(userId: string, input: ToolInput) {
  const where: Record<string, unknown> = { userId };
  if (input.includeInactive !== true) where.active = true;
  if (typeof input.query === "string" && input.query.trim()) {
    const q = input.query.trim();
    where.OR = [
      { label: { contains: q, mode: "insensitive" } },
      { note: { contains: q, mode: "insensitive" } },
    ];
  }
  const rules = await prisma.fixedExpense.findMany({ where, orderBy: { createdAt: "asc" } });
  const counts = await prisma.expense.groupBy({
    by: ["fixedSourceId"],
    where: { userId, fixedSourceId: { in: rules.map((r) => r.id) } },
    _count: true,
  });
  const countById = new Map(counts.map((c) => [c.fixedSourceId, c._count]));

  return {
    rules: rules.map((r) => ({
      ruleId: r.id,
      label: r.label,
      ...(r.note && { note: r.note }),
      category: r.category,
      amount: Number(r.amount),
      currency: r.currency,
      dueDay: r.dueDay,
      activeFrom: fmtYM(r.startYear, r.startMonth),
      activeUntil: r.endYear != null && r.endMonth != null ? fmtYM(r.endYear, r.endMonth) : "ongoing",
      active: r.active,
      generatedExpenseCount: countById.get(r.id) ?? 0,
    })),
    note:
      "Each rule generates one ledger expense per month in its range. Changing a rule updates every affected month; changing one generated expense changes only that month.",
  };
}

async function getFinancialOverview(userId: string, now: Date) {
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const monthStart = new Date(year, month - 1, 1);
  const nextMonthStart = new Date(year, month, 1);

  const [user, periods, sources, bonuses, monthAgg, fixedRules, closedCount] = await Promise.all([
    prisma.user.findUnique({ where: { id: userId } }),
    prisma.salaryPeriod.findMany({ where: { userId } }),
    prisma.incomeSource.findMany({ where: { userId } }),
    prisma.bonus.findMany({ where: { userId, year } }),
    prisma.expense.aggregate({
      _count: true,
      _sum: { amount: true },
      where: { userId, spentAt: { gte: monthStart, lt: nextMonthStart } },
    }),
    prisma.fixedExpense.findMany({ where: { userId, active: true } }),
    prisma.monthClose.count({ where: { userId } }),
  ]);
  if (!user) return { error: "user not found" };

  const active = activeSalaryForMonth(periods.map(toUiSalaryPeriod), year, month);
  const otherIncome = recurringMonthlyIncome(sources.map(toUiIncomeSource), year, month);
  const cmp = (aY: number, aM: number, bY: number, bM: number) => (aY !== bY ? aY - bY : aM - bM);
  const activeRules = fixedRules.filter((f) => {
    const started = cmp(year, month, f.startYear, f.startMonth) >= 0;
    const notEnded = f.endYear == null || f.endMonth == null || cmp(year, month, f.endYear, f.endMonth) <= 0;
    return started && notEnded;
  });
  const spent = Number(monthAgg._sum.amount ?? 0);
  const budget = Number(user.monthlyBudget);

  return {
    today: fmtDate(now),
    displayCurrency: user.currency,
    income: {
      monthlyTakeHomeSalary: active?.monthlySalary ?? 0,
      grossSalary: active?.grossSalary ?? 0,
      deductions: active?.deductions ?? 0,
      otherRecurringMonthlyIncome: otherIncome,
      totalMonthlyIncome: (active?.monthlySalary ?? 0) + otherIncome,
      payDay: user.payDay,
      payFrequency: user.payFrequency,
      bonusesThisYear: bonuses.map((b) => ({ bonusId: b.id, month: b.month, amount: Number(b.amount), label: b.label })),
    },
    savings: {
      goal: Number(user.savingsGoal),
      saved: Number(user.saved),
      remainingToGoal: Math.max(0, Number(user.savingsGoal) - Number(user.saved)),
    },
    thisMonth: {
      month: fmtYM(year, month),
      spentSoFar: spent,
      expenseCount: monthAgg._count,
      monthlyBudget: budget,
      budgetRemaining: budget > 0 ? budget - spent : null,
    },
    recurringCommitments: {
      activeRuleCount: activeRules.length,
      totalMonthlyAmount: activeRules.reduce((a, f) => a + Number(f.amount), 0),
    },
    closedMonthCount: closedCount,
  };
}

async function analyzeSpending(userId: string, input: ToolInput) {
  const from = parseDay(input.dateFrom);
  const to = parseDay(input.dateTo, true);
  if (!from || !to) return { error: "dateFrom and dateTo must be YYYY-MM-DD or YYYY-MM" };
  if (to.getTime() - from.getTime() > 3 * 366 * 24 * 3600 * 1000) {
    return { error: "range too large — max 3 years per call" };
  }
  const groupBy = input.groupBy === "month" || input.groupBy === "tag" ? input.groupBy : "category";

  const rows = await prisma.expense.findMany({
    where: { userId, spentAt: { gte: from, lte: to } },
    select: { spentAt: true, amount: true, category: true, tags: true, fixed: true },
  });

  const groups = new Map<string, { total: number; count: number; recurring: number }>();
  let total = 0;
  let recurringTotal = 0;
  for (const r of rows) {
    const amt = Number(r.amount);
    total += amt;
    if (r.fixed) recurringTotal += amt;
    const keys =
      groupBy === "category"
        ? [r.category as string]
        : groupBy === "month"
          ? [fmtYM(r.spentAt.getFullYear(), r.spentAt.getMonth() + 1)]
          : r.tags.length > 0
            ? r.tags
            : ["(untagged)"];
    for (const k of keys) {
      const g = groups.get(k) ?? { total: 0, count: 0, recurring: 0 };
      g.total += amt;
      g.count += 1;
      if (r.fixed) g.recurring += amt;
      groups.set(k, g);
    }
  }

  return {
    range: { from: fmtDate(from), to: fmtDate(to) },
    overall: { total, expenseCount: rows.length, recurringPortion: recurringTotal, discretionaryPortion: total - recurringTotal },
    groupedBy: groupBy,
    groups: [...groups.entries()]
      .sort((a, b) => b[1].total - a[1].total)
      .slice(0, 40)
      .map(([key, g]) => ({ [groupBy]: key, total: g.total, count: g.count, recurringPortion: g.recurring })),
    ...(groupBy === "tag" && { note: "an expense can carry several tags, so tag totals may overlap" }),
  };
}

async function projectSavings(userId: string, input: ToolInput, now: Date) {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) return { error: "user not found" };

  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const target = toNum(input.targetAmount) ?? Number(user.savingsGoal);
  const saved = Number(user.saved);

  const [periods, sources] = await Promise.all([
    prisma.salaryPeriod.findMany({ where: { userId } }),
    prisma.incomeSource.findMany({ where: { userId } }),
  ]);
  const salary = activeSalaryForMonth(periods.map(toUiSalaryPeriod), year, month)?.monthlySalary ?? 0;
  const otherIncome = recurringMonthlyIncome(sources.map(toUiIncomeSource), year, month);
  const monthlyIncome = salary + otherIncome;

  // Average spend over the last 3 FULL calendar months (falls back to whatever
  // history exists; a brand-new user gets the current month so far).
  const windowStart = new Date(year, month - 4, 1);
  const windowEnd = new Date(year, month - 1, 1);
  const past = await prisma.expense.findMany({
    where: { userId, spentAt: { gte: windowStart, lt: windowEnd } },
    select: { spentAt: true, amount: true, category: true },
  });
  let avgSpend: number;
  let windowLabel: string;
  let byCategory: { category: string; monthlyAverage: number }[] = [];
  if (past.length > 0) {
    const monthsSeen = new Set(past.map((r) => `${r.spentAt.getFullYear()}-${r.spentAt.getMonth()}`)).size;
    const div = Math.max(1, monthsSeen);
    avgSpend = past.reduce((a, r) => a + Number(r.amount), 0) / div;
    windowLabel = `average of last ${div} full month(s)`;
    const catTotals = new Map<string, number>();
    for (const r of past) catTotals.set(r.category, (catTotals.get(r.category) ?? 0) + Number(r.amount));
    byCategory = [...catTotals.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([category, t]) => ({ category, monthlyAverage: Math.round((t / div) * 100) / 100 }));
  } else {
    const cur = await prisma.expense.aggregate({
      _sum: { amount: true },
      where: { userId, spentAt: { gte: new Date(year, month - 1, 1) } },
    });
    avgSpend = Number(cur._sum.amount ?? 0);
    windowLabel = "current month so far (no full-month history yet)";
  }

  const assumedSpend = toNum(input.monthlySpendOverride) ?? avgSpend;
  const monthlyNet = monthlyIncome - assumedSpend;
  const remaining = Math.max(0, target - saved);
  const monthsToTarget = remaining === 0 ? 0 : monthlyNet > 0 ? Math.ceil(remaining / monthlyNet) : null;
  let estimatedArrival: string | null = null;
  if (monthsToTarget != null) {
    const d = new Date(year, month - 1 + monthsToTarget, 1);
    estimatedArrival = fmtYM(d.getFullYear(), d.getMonth() + 1);
  }

  return {
    target,
    saved,
    remainingToTarget: remaining,
    monthlyIncome: { salary, otherRecurring: otherIncome, total: monthlyIncome },
    monthlySpend: {
      basis: toNum(input.monthlySpendOverride) != null ? "override (what-if)" : windowLabel,
      amount: Math.round(assumedSpend * 100) / 100,
    },
    monthlyNetSavings: Math.round(monthlyNet * 100) / 100,
    monthsToTarget,
    estimatedArrival,
    ...(monthsToTarget == null && remaining > 0 && {
      note: "monthly spend meets or exceeds income at this rate — the target is unreachable without changes",
    }),
    recentSpendByCategory: byCategory,
  };
}

async function getClosedMonths(userId: string) {
  const rows = await prisma.monthClose.findMany({
    where: { userId },
    orderBy: [{ year: "desc" }, { month: "desc" }],
  });
  return { closedMonths: rows.map((r) => fmtYM(r.year, r.month)) };
}

async function getPreferences(userId: string) {
  const rows = await prisma.userPreference.findMany({ where: { userId } });
  return {
    preferences: rows.map((r) => ({ key: r.key, value: r.value })),
    ...(rows.length === 0 && { note: "no saved preferences yet — avoid assuming what the user values" }),
  };
}

async function findBonuses(userId: string, input: ToolInput) {
  const where: Record<string, unknown> = { userId };
  const y = toNum(input.year);
  if (y != null) where.year = Math.round(y);
  const rows = await prisma.bonus.findMany({
    where,
    orderBy: [{ year: "desc" }, { month: "asc" }],
  });
  return {
    bonuses: rows.map((b) => ({
      bonusId: b.id,
      year: b.year,
      month: b.month,
      amount: Number(b.amount),
      label: b.label,
    })),
    ...(rows.length === 0 && {
      note: `no bonuses recorded${y != null ? ` for ${Math.round(y)}` : ""}`,
    }),
  };
}

// ── write proposals (Slice 2) ────────────────────────────────
// Each builds a self-contained Proposal (no DB writes). The engine assigns the
// real proposal.id (the tool_use block id) after these return.

const CURRENCY_SYMBOL: Record<Currency, string> = { SGD: "S$", MYR: "RM", CNY: "¥", USD: "$" };
const fmtMoney = (amount: number, currency: Currency) =>
  `${CURRENCY_SYMBOL[currency] ?? ""}${amount.toFixed(2)}`;

/** "YYYY-MM" if that calendar month is hard-closed for the user, else null. */
async function closedMonthKey(userId: string, d: Date): Promise<string | null> {
  const year = d.getFullYear();
  const month = d.getMonth() + 1;
  const row = await prisma.monthClose.findUnique({
    where: { userId_year_month: { userId, year, month } },
  });
  return row ? fmtYM(year, month) : null;
}

/** Parse an agent-supplied YYYY-MM-DD to local noon (avoids day-boundary TZ drift). */
function parseSpendDate(s: unknown): Date | null {
  const d = parseDay(s);
  if (!d) return null;
  d.setHours(12, 0, 0, 0);
  return d;
}

function pickCategory(v: unknown): CategoryKey | null {
  return typeof v === "string" && WRITABLE_CATEGORIES.includes(v as CategoryKey)
    ? (v as CategoryKey)
    : null;
}
/** Like pickCategory but allows "family" too — recurring rules support it, plain
 *  expenses don't (WRITABLE_CATEGORIES intentionally excludes it). */
function pickCategoryAny(v: unknown): CategoryKey | null {
  return typeof v === "string" && ALL_CATEGORIES.includes(v as CategoryKey) ? (v as CategoryKey) : null;
}
function pickCurrency(v: unknown): Currency | null {
  return typeof v === "string" && WRITABLE_CURRENCIES.includes(v as Currency) ? (v as Currency) : null;
}

/** A shared "not a proposal" shape so Claude can recover (ask again / re-search). */
type ToolError = { error: string };

async function proposeCreateExpense(
  userId: string,
  input: ToolInput,
  now: Date,
): Promise<WriteToolOutput | ToolError> {
  const amount = toNum(input.amount);
  if (amount == null || amount <= 0) return { error: "amount must be a positive number" };
  const category = pickCategory(input.category);
  if (!category) return { error: `category must be one of: ${WRITABLE_CATEGORIES.join(", ")}` };
  const currency = pickCurrency(input.currency) ?? "SGD";

  let when = now;
  if (input.date != null) {
    const parsed = parseSpendDate(input.date);
    if (!parsed) return { error: "date must be YYYY-MM-DD" };
    when = parsed;
  }
  const tags = normalizeTags(Array.isArray(input.tags) ? (input.tags as string[]) : []);
  const note = typeof input.note === "string" ? input.note.trim() : "";
  const fields: ExpenseFields = { amount, currency, category, note, tags, spentAt: when.toISOString() };
  const closedMonth = await closedMonthKey(userId, when);

  return {
    proposal: {
      id: "",
      kind: "create_expense",
      summary: `Add ${fmtMoney(amount, currency)} · ${category}${note ? ` · ${note}` : ""}`,
      closedMonth,
      create: fields,
    },
    modelResult:
      "Add-expense proposal is on screen as a confirmation card — nothing is saved yet. " +
      "Briefly ask the user to review and Confirm it (don't restate every field)." +
      (closedMonth
        ? ` Note: ${closedMonth} is closed; the card lets them add anyway or cancel.`
        : " The target month is currently OPEN — do NOT mention closing/reopening."),
  };
}

/** Build ExpenseFields from a DB row. */
function rowToFields(r: {
  amount: unknown;
  currency: string;
  category: string;
  note: string | null;
  tags: string[];
  spentAt: Date;
}): ExpenseFields {
  return {
    amount: Number(r.amount),
    currency: r.currency as Currency,
    category: r.category as CategoryKey,
    note: r.note ?? "",
    tags: r.tags,
    spentAt: r.spentAt.toISOString(),
  };
}

async function proposeUpdateExpense(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const id = toNum(input.id);
  if (id == null || !Number.isInteger(id)) {
    return { error: "pass the numeric id of the expense (from find_expenses)" };
  }
  const row = await prisma.expense.findFirst({
    where: { id, userId },
    select: {
      id: true, amount: true, currency: true, category: true,
      note: true, tags: true, spentAt: true, fixed: true, fixedSourceId: true,
    },
  });
  if (!row) return { error: "no expense with that id — call find_expenses to get the right id" };

  const before = rowToFields(row);
  const after: ExpenseFields = { ...before };
  let changed = false;

  if (input.amount !== undefined) {
    const a = toNum(input.amount);
    if (a == null || a <= 0) return { error: "amount must be a positive number" };
    after.amount = a; changed = true;
  }
  if (input.category !== undefined) {
    const c = pickCategory(input.category);
    if (!c) return { error: `category must be one of: ${WRITABLE_CATEGORIES.join(", ")}` };
    after.category = c; changed = true;
  }
  if (input.currency !== undefined) {
    const cur = pickCurrency(input.currency);
    if (!cur) return { error: `currency must be one of: ${WRITABLE_CURRENCIES.join(", ")}` };
    after.currency = cur; changed = true;
  }
  if (input.note !== undefined) {
    after.note = typeof input.note === "string" ? input.note.trim() : "";
    changed = true;
  }
  if (input.tags !== undefined) {
    after.tags = normalizeTags(Array.isArray(input.tags) ? (input.tags as string[]) : []);
    changed = true;
  }
  if (input.date !== undefined) {
    const parsed = parseSpendDate(input.date);
    if (!parsed) return { error: "date must be YYYY-MM-DD" };
    after.spentAt = parsed.toISOString();
    changed = true;
  }
  if (!changed) return { error: "no changes given — say what to change (amount, category, note, tags, date…)" };

  // Either the row's current month or (if the date moves) the target month being
  // closed will block the edit — surface whichever is closed so the card can warn.
  const curClosed = await closedMonthKey(userId, new Date(before.spentAt!));
  const newClosed =
    after.spentAt !== before.spentAt ? await closedMonthKey(userId, new Date(after.spentAt!)) : null;
  const closedMonth = curClosed ?? newClosed;
  const recurringWarning = row.fixed || row.fixedSourceId != null;

  return {
    proposal: {
      id: "",
      kind: "update_expense",
      summary: `Update ${fmtMoney(before.amount, before.currency)} · ${before.category}`,
      closedMonth,
      recurringWarning,
      expenseId: row.id,
      before,
      after,
    },
    modelResult:
      "Edit proposal (before→after) is on screen as a confirmation card — nothing is saved yet. " +
      "Ask the user to review and Confirm." +
      (recurringWarning
        ? " Heads-up: this row was generated by a recurring rule, so confirming changes ONLY this month. To change the recurring commitment across months, use edit_recurring instead."
        : "") +
      (closedMonth
        ? ` Note: ${closedMonth} is closed; the card lets them edit anyway or cancel.`
        : " The month is currently OPEN — do NOT mention closing/reopening."),
  };
}

async function proposeDeleteExpense(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const id = toNum(input.id);
  if (id == null || !Number.isInteger(id)) {
    return { error: "pass the numeric id of the expense (from find_expenses)" };
  }
  const row = await prisma.expense.findFirst({
    where: { id, userId },
    select: {
      id: true, amount: true, currency: true, category: true,
      note: true, tags: true, spentAt: true, fixed: true, fixedSourceId: true,
    },
  });
  if (!row) return { error: "no expense with that id — call find_expenses to get the right id" };

  const target = rowToFields(row);
  const closedMonth = await closedMonthKey(userId, row.spentAt);
  const recurringWarning = row.fixed || row.fixedSourceId != null;

  return {
    proposal: {
      id: "",
      kind: "delete_expense",
      summary: `Delete ${fmtMoney(target.amount, target.currency)} · ${target.category}${target.note ? ` · ${target.note}` : ""}`,
      closedMonth,
      recurringWarning,
      expenseId: row.id,
      target,
    },
    modelResult: closedMonth
      ? `That expense is in a closed month (${closedMonth}) — it can't be deleted while the month is closed. Offer to reopen the month first via set_month_status (confirm-gated), then delete.`
      : "Delete proposal is on screen as a confirmation card — nothing is deleted yet. Ask the user to confirm." +
        (recurringWarning
          ? " Note: this row came from a recurring rule; deleting it removes only this month's entry."
          : "") +
        " The month is currently OPEN — do NOT mention closing/reopening.",
  };
}

// ── recurring-rule edit proposal (Slice 2b) ──────────────────
// The smart edit: routes (on confirm) to changeFixedAmount (rate change, keeps
// history) or updateFixedExpense (redefine, rewrite all months). The tool only
// PROPOSES — it resolves the rule, computes the affected month span + which of
// those are hard-closed, and hands the client a card to confirm.

const cmpYM = (aY: number, aM: number, bY: number, bM: number) => (aY !== bY ? aY - bY : aM - bM);

/** The materialized-affected months (start → min(today, end)) as "YYYY-MM" keys. */
function monthsInRange(
  startY: number,
  startM: number,
  endY: number | null,
  endM: number | null,
  nowY: number,
  nowM: number,
): string[] {
  const out: string[] = [];
  let cy = startY;
  let cm = startM;
  while (cmpYM(cy, cm, nowY, nowM) <= 0) {
    if (endY != null && endM != null && cmpYM(cy, cm, endY, endM) > 0) break;
    out.push(fmtYM(cy, cm));
    if (cm >= 12) { cy += 1; cm = 1; } else { cm += 1; }
    if (out.length > 600) break; // safety against a pathological range
  }
  return out;
}

async function closedKeySet(userId: string): Promise<Set<string>> {
  const rows = await prisma.monthClose.findMany({
    where: { userId },
    select: { year: true, month: true },
  });
  return new Set(rows.map((r) => `${r.year}-${r.month}`));
}

async function proposeEditRecurring(
  userId: string,
  input: ToolInput,
  now: Date,
): Promise<WriteToolOutput | ToolError> {
  const ruleId = toNum(input.ruleId);
  if (ruleId == null || !Number.isInteger(ruleId)) {
    return { error: "pass the numeric ruleId of the recurring rule (from find_recurring)" };
  }
  const rule = await prisma.fixedExpense.findFirst({ where: { id: ruleId, userId } });
  if (!rule) return { error: "no recurring rule with that id — call find_recurring to get the ruleId" };

  const mode = input.mode === "redefine" ? "redefine" : input.mode === "rate_change" ? "rate_change" : null;
  if (!mode) {
    return { error: "mode must be 'rate_change' (amount changes from a month onward) or 'redefine' (rewrite the whole rule)" };
  }

  const nowY = now.getFullYear();
  const nowM = now.getMonth() + 1;

  const before: RecurringSnapshot = {
    label: rule.label,
    amount: Number(rule.amount),
    currency: rule.currency as Currency,
    category: rule.category as CategoryKey,
    note: rule.note ?? "",
    dueDay: rule.dueDay,
    activeFrom: fmtYM(rule.startYear, rule.startMonth),
    activeUntil: rule.endYear != null && rule.endMonth != null ? fmtYM(rule.endYear, rule.endMonth) : "ongoing",
  };

  // Resolve mode-specific values, the affected month RANGE, and the after-snapshot.
  let range: { startYear: number; startMonth: number; endYear: number | null; endMonth: number | null };
  let after: RecurringSnapshot;
  const recurring: NonNullable<Proposal["recurring"]> = {
    ruleId,
    mode,
    before,
    after: before, // placeholder, set below
    range: { startYear: rule.startYear, startMonth: rule.startMonth, endYear: rule.endYear, endMonth: rule.endMonth },
    impact: { monthCount: 0, firstMonth: before.activeFrom, lastMonth: before.activeFrom },
    closedInRange: [],
  };

  if (mode === "rate_change") {
    const amt = toNum(input.newAmount);
    if (amt == null || amt <= 0) return { error: "newAmount must be a positive number for a rate_change" };
    let fy = nowY;
    let fm = nowM;
    if (input.fromMonth != null) {
      const d = parseDay(input.fromMonth); // accepts YYYY-MM
      if (!d) return { error: "fromMonth must be YYYY-MM" };
      fy = d.getFullYear();
      fm = d.getMonth() + 1;
    }
    range = { startYear: fy, startMonth: fm, endYear: rule.endYear, endMonth: rule.endMonth };
    after = { ...before, amount: amt };
    recurring.fromYear = fy;
    recurring.fromMonth = fm;
    recurring.newAmount = amt;
  } else {
    // redefine — only the field(s) the model set. Active start/end are NOT editable
    // here (use the manual editor); the affected range stays the rule's own span.
    const changes: RecurringChanges = {};
    if (input.amount !== undefined) {
      const a = toNum(input.amount);
      if (a == null || a <= 0) return { error: "amount must be a positive number" };
      changes.amount = a;
    }
    if (input.label !== undefined) {
      const l = typeof input.label === "string" ? input.label.trim().slice(0, 40) : "";
      if (l) changes.label = l;
    }
    if (input.note !== undefined) {
      changes.note = typeof input.note === "string" ? input.note.trim().slice(0, 120) : "";
    }
    if (input.category !== undefined) {
      const c = pickCategory(input.category);
      if (!c) return { error: `category must be one of: ${WRITABLE_CATEGORIES.join(", ")}` };
      changes.category = c;
    }
    if (input.currency !== undefined) {
      const cur = pickCurrency(input.currency);
      if (!cur) return { error: `currency must be one of: ${WRITABLE_CURRENCIES.join(", ")}` };
      changes.currency = cur;
    }
    if (input.dueDay !== undefined) {
      const d = toNum(input.dueDay);
      if (d == null || d < 1 || d > 31) return { error: "dueDay must be 1–31" };
      changes.dueDay = Math.round(d);
    }
    if (Object.keys(changes).length === 0) {
      return { error: "no changes given — for redefine, say what to change (amount, label, category, currency, note, dueDay)" };
    }
    range = { startYear: rule.startYear, startMonth: rule.startMonth, endYear: rule.endYear, endMonth: rule.endMonth };
    after = {
      label: changes.label ?? before.label,
      amount: changes.amount ?? before.amount,
      currency: changes.currency ?? before.currency,
      category: changes.category ?? before.category,
      note: changes.note ?? before.note,
      dueDay: changes.dueDay ?? before.dueDay,
      activeFrom: before.activeFrom,
      activeUntil: before.activeUntil,
    };
    recurring.changes = changes;
  }

  recurring.after = after;
  recurring.range = range;

  const months = monthsInRange(range.startYear, range.startMonth, range.endYear, range.endMonth, nowY, nowM);
  recurring.impact = {
    monthCount: months.length,
    firstMonth: months[0] ?? fmtYM(range.startYear, range.startMonth),
    lastMonth: months[months.length - 1] ?? fmtYM(range.startYear, range.startMonth),
  };

  const closed = await closedKeySet(userId);
  recurring.closedInRange = closedMonthsInRange(
    closed,
    range.startYear,
    range.startMonth,
    range.endYear,
    range.endMonth,
    nowY,
    nowM,
  ).map((h) => fmtYM(h.year, h.month));

  const amountMoved = after.amount !== before.amount;
  const summary =
    mode === "rate_change"
      ? `Recurring ${before.label}: ${fmtMoney(before.amount, before.currency)} → ${fmtMoney(after.amount, after.currency)} from ${recurring.impact.firstMonth}`
      : `Recurring ${before.label}${amountMoved ? `: ${fmtMoney(before.amount, before.currency)} → ${fmtMoney(after.amount, after.currency)}` : " updated"}`;

  return {
    proposal: { id: "", kind: "edit_recurring", summary, recurring },
    modelResult:
      "A recurring-rule edit card is on screen — NOTHING is saved yet. It propagates across every affected " +
      `month + the ledger/calendar/dashboard/income. Briefly ask the user to review & Confirm (don't restate all fields). ` +
      (mode === "rate_change"
        ? `This is a rate change: months before ${recurring.impact.firstMonth} keep ${fmtMoney(before.amount, before.currency)}.`
        : `This redefines the rule across all ${recurring.impact.monthCount} affected month(s).`) +
      (recurring.closedInRange.length > 0
        ? ` Note: ${recurring.closedInRange.join(", ")} ${recurring.closedInRange.length === 1 ? "is" : "are"} closed — the card lets them keep those frozen or override.`
        : " All affected months are currently OPEN — do NOT mention closing/reopening."),
  };
}

function proposeSetPreference(input: ToolInput): WriteToolOutput | ToolError {
  const key = typeof input.key === "string" ? input.key.trim().toLowerCase().slice(0, 40) : "";
  const value = typeof input.value === "string" ? input.value.trim().slice(0, 300) : "";
  if (!key) return { error: "provide a short key for the preference (e.g. 'gaming', 'priorities')" };
  if (!value) return { error: "provide the value to remember (what the user said they value)" };
  return {
    proposal: {
      id: "",
      kind: "set_preference",
      summary: `Remember: ${key} — ${value}`,
      preference: { key, value },
    },
    modelResult:
      "A 'remember this preference' card is on screen — nothing is saved yet. Ask the user to confirm saving it, " +
      "and note you'll keep it in mind for future suggestions. Don't restate the whole thing.",
  };
}

// ── create a brand-new recurring rule (Slice 2c) ─────────────
// Unlike edit_recurring (which resolves an EXISTING ruleId), this builds a fresh
// FixedExpense definition. Confirming routes to addFixedExpense, which materializes
// due months immediately (skipping any that are hard-closed) — mirrors what the
// Recurring page's own "Add" does.

async function proposeCreateRecurring(
  userId: string,
  input: ToolInput,
  now: Date,
): Promise<WriteToolOutput | ToolError> {
  const label = typeof input.label === "string" ? input.label.trim().slice(0, 40) : "";
  if (!label) return { error: "provide a label/name for the recurring commitment" };
  const amount = toNum(input.amount);
  if (amount == null || amount <= 0) return { error: "amount must be a positive number" };
  const category = pickCategoryAny(input.category);
  if (!category) return { error: `category must be one of: ${ALL_CATEGORIES.join(", ")}` };
  const currency = pickCurrency(input.currency) ?? "SGD";
  const note = typeof input.note === "string" ? input.note.trim().slice(0, 120) : "";
  const dueDayRaw = toNum(input.dueDay);
  const dueDay = dueDayRaw != null ? Math.min(31, Math.max(1, Math.round(dueDayRaw))) : 1;

  let startYear = now.getFullYear();
  let startMonth = now.getMonth() + 1;
  if (input.startMonth != null) {
    const d = parseDay(input.startMonth);
    if (!d) return { error: "startMonth must be YYYY-MM" };
    startYear = d.getFullYear();
    startMonth = d.getMonth() + 1;
  }
  let endYear: number | null = null;
  let endMonth: number | null = null;
  if (input.endMonth != null) {
    const d = parseDay(input.endMonth);
    if (!d) return { error: "endMonth must be YYYY-MM" };
    endYear = d.getFullYear();
    endMonth = d.getMonth() + 1;
    if (cmpYM(endYear, endMonth, startYear, startMonth) < 0) {
      return { error: "endMonth can't be before startMonth" };
    }
  }

  const fields: RecurringCreateFields = {
    label,
    note,
    category,
    currency,
    amount,
    dueDay,
    startYear,
    startMonth,
    endYear,
    endMonth,
  };

  // Which already-due months in [start, today] (capped at end) are hard-closed —
  // those won't get a generated entry unless the user overrides on the card.
  const closed = await closedKeySet(userId);
  const closedInRange = closedMonthsInRange(
    closed,
    startYear,
    startMonth,
    endYear,
    endMonth,
    now.getFullYear(),
    now.getMonth() + 1,
  ).map((h) => fmtYM(h.year, h.month));

  return {
    proposal: {
      id: "",
      kind: "create_recurring",
      summary: `Set up recurring ${label} · ${fmtMoney(amount, currency)}/mo from ${fmtYM(startYear, startMonth)}`,
      recurringCreate: fields,
      closedInRange,
    },
    modelResult:
      "A new-recurring-rule card is on screen — nothing is saved yet. Once confirmed it generates a real " +
      "expense every month from the start month onward (retroactively materializing already-due months). " +
      "Ask the user to review & Confirm." +
      (closedInRange.length > 0
        ? ` NOTE: ${closedInRange.join(", ")} ${closedInRange.length === 1 ? "is" : "are"} hard-CLOSED, so by ` +
          `default no entry is added there — mention this, and note the card lets them add into the closed ` +
          `month(s) anyway or skip them. (If they'd rather fully reopen a closed month first, you can offer a ` +
          `[[suggest:Reopen ${closedInRange[0]}]] chip.)`
        : ""),
  };
}

// ── month reopen/close proposal (Slice 2b fix batch) ─────────
// Lets the assistant reopen/close a month's books (confirm-gated) instead of sending
// the user off to the Ledger page. Checks the LIVE status so it never proposes a
// no-op (already open / already closed).

async function proposeSetMonthStatus(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const parsed = parseDay(input.month); // accepts YYYY-MM
  if (!parsed) return { error: "month must be YYYY-MM (e.g. 2026-06)" };
  const year = parsed.getFullYear();
  const month = parsed.getMonth() + 1;
  const action = input.action === "close" ? "close" : input.action === "reopen" ? "reopen" : null;
  if (!action) return { error: "action must be 'reopen' or 'close'" };

  const monthLabel = new Date(year, month - 1, 1).toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });
  const isClosed = (await closedMonthKey(userId, new Date(year, month - 1, 1))) != null;
  if (action === "reopen" && !isClosed) {
    return { error: `${monthLabel} is already open — there's nothing to reopen.` };
  }
  if (action === "close" && isClosed) {
    return { error: `${monthLabel} is already closed.` };
  }

  return {
    proposal: {
      id: "",
      kind: "set_month_status",
      summary: `${action === "reopen" ? "Reopen" : "Close"} ${monthLabel}`,
      monthStatus: { year, month, monthLabel, action },
    },
    modelResult:
      `A ${action}-month card is on screen — nothing has changed yet. Ask the user to review & Confirm. ` +
      (action === "reopen"
        ? `Reopening ${monthLabel} unlocks it so its entries can be added/edited/deleted again.`
        : `Closing ${monthLabel} locks all its entries until it's reopened.`),
  };
}

// ── income-management proposals (Slice 2d) ───────────────────
// WRITE counterparts to get_financial_overview. Each resolves the CURRENT values (so
// the card shows before→after and the model has honest context) and returns a proposal
// — nothing is saved until Confirm → executeAssistantAction routes to the same server
// actions the Income page uses (updateIncomeSettings / addSalaryPeriod / bonus CRUD).

const monthYearLabel = (y: number, m: number) =>
  new Date(y, m - 1, 1).toLocaleDateString("en-US", { month: "short", year: "numeric" });

async function userCurrency(userId: string): Promise<Currency> {
  const user = await prisma.user.findUnique({ where: { id: userId }, select: { currency: true } });
  return (user?.currency as Currency) ?? "SGD";
}

async function proposeSetSavingsGoal(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) return { error: "user not found" };
  const currency = user.currency as Currency;

  const changes: SavingsSettingsFields = {};
  const before: SavingsSettingsFields = {};

  const goal = toNum(input.savingsGoal);
  if (goal != null) {
    if (goal < 0) return { error: "savingsGoal can't be negative" };
    changes.savingsGoal = goal;
    before.savingsGoal = Number(user.savingsGoal);
  }
  const saved = toNum(input.saved);
  if (saved != null) {
    if (saved < 0) return { error: "saved can't be negative" };
    changes.saved = saved;
    before.saved = Number(user.saved);
  }
  const budget = toNum(input.monthlyBudget);
  if (budget != null) {
    if (budget < 0) return { error: "monthlyBudget can't be negative" };
    changes.monthlyBudget = budget;
    before.monthlyBudget = Number(user.monthlyBudget);
  }
  const payDay = toNum(input.payDay);
  if (payDay != null) {
    changes.payDay = Math.min(31, Math.max(1, Math.round(payDay)));
    before.payDay = user.payDay;
  }
  if (typeof input.payFrequency === "string" && input.payFrequency.trim()) {
    changes.payFrequency = input.payFrequency.trim().slice(0, 24);
    before.payFrequency = user.payFrequency;
  }
  if (Object.keys(changes).length === 0) {
    return { error: "say what to change: savings goal, saved amount, monthly budget, pay day, or pay frequency" };
  }

  const parts: string[] = [];
  if (changes.savingsGoal != null) parts.push(`goal ${fmtMoney(changes.savingsGoal, currency)}`);
  if (changes.saved != null) parts.push(`saved ${fmtMoney(changes.saved, currency)}`);
  if (changes.monthlyBudget != null) parts.push(`budget ${fmtMoney(changes.monthlyBudget, currency)}`);
  if (changes.payDay != null) parts.push(`pay day ${changes.payDay}`);
  if (changes.payFrequency != null) parts.push(`pay ${changes.payFrequency}`);

  return {
    proposal: {
      id: "",
      kind: "set_savings_goal",
      summary: `Update ${parts.join(", ")}`,
      savingsGoal: { currency, changes, before },
    },
    modelResult:
      "A savings/settings change card is on screen — nothing is saved yet. Briefly ask the user to review & Confirm (don't restate every field).",
  };
}

async function proposeAdjustSalary(
  userId: string,
  input: ToolInput,
  now: Date,
): Promise<WriteToolOutput | ToolError> {
  const amount = toNum(input.monthlySalary);
  if (amount == null || amount <= 0) return { error: "monthlySalary must be a positive number" };

  let ey = now.getFullYear();
  let em = now.getMonth() + 1;
  if (input.effectiveMonth != null) {
    const d = parseDay(input.effectiveMonth); // accepts YYYY-MM
    if (!d) return { error: "effectiveMonth must be YYYY-MM" };
    ey = d.getFullYear();
    em = d.getMonth() + 1;
  }
  const grossInput = toNum(input.grossSalary);
  const dedInput = toNum(input.deductions);
  if (grossInput != null && grossInput < 0) return { error: "grossSalary can't be negative" };
  if (dedInput != null && dedInput < 0) return { error: "deductions can't be negative" };
  const labelInput = typeof input.label === "string" ? input.label.trim().slice(0, 40) : "";

  const [user, periods] = await Promise.all([
    prisma.user.findUnique({ where: { id: userId } }),
    prisma.salaryPeriod.findMany({ where: { userId } }),
  ]);
  if (!user) return { error: "user not found" };
  const currency = user.currency as Currency;
  const uiPeriods = periods.map(toUiSalaryPeriod);
  const active = activeSalaryForMonth(uiPeriods, ey, em);
  const previousTakeHome = active ? active.monthlySalary : null;
  // The period (if any) that already starts exactly at this month — correcting it.
  const existing = uiPeriods.find((p) => p.year === ey && p.month === em) ?? null;
  const overwritesExisting = existing != null;

  // Preserve the existing period's gross/deductions/label when the user is correcting
  // it and didn't restate them — addSalaryPeriod's upsert would otherwise reset them.
  const gross = grossInput != null ? grossInput : existing ? existing.grossSalary : null;
  const deductions = dedInput != null ? dedInput : existing ? existing.deductions : null;
  const label = labelInput || existing?.label || "";

  const fields: SalaryFields = {
    effectiveYear: ey,
    effectiveMonth: em,
    monthlySalary: amount,
    grossSalary: gross,
    deductions,
    label,
  };

  return {
    proposal: {
      id: "",
      kind: "adjust_salary",
      summary: `Salary → ${fmtMoney(amount, currency)}/mo from ${fmtYM(ey, em)}`,
      salary: { currency, fields, previousTakeHome, overwritesExisting },
    },
    modelResult:
      "A salary-change card is on screen — nothing is saved yet. Ask the user to review & Confirm. " +
      (overwritesExisting
        ? `This CORRECTS the salary period that already starts ${monthYearLabel(ey, em)}.`
        : `This sets the salary effective from ${monthYearLabel(ey, em)} onward; earlier months keep their current salary` +
          (previousTakeHome != null ? ` (${fmtMoney(previousTakeHome, currency)})` : "") +
          ".") +
      (gross == null && deductions == null
        ? " Gross/CPF weren't given — that's fine (they're optional; the card's Edit can add them)."
        : ""),
  };
}

async function proposeCreateBonus(
  userId: string,
  input: ToolInput,
  now: Date,
): Promise<WriteToolOutput | ToolError> {
  const amount = toNum(input.amount);
  if (amount == null || amount <= 0) return { error: "amount must be a positive number" };
  const label =
    typeof input.label === "string" && input.label.trim() ? input.label.trim().slice(0, 40) : "Bonus";
  const yRaw = toNum(input.year);
  const year = yRaw != null ? Math.round(yRaw) : now.getFullYear();
  const mRaw = toNum(input.month);
  const month = mRaw != null ? Math.min(12, Math.max(1, Math.round(mRaw))) : now.getMonth() + 1;
  const currency = await userCurrency(userId);
  const fields: BonusFields = { year, month, amount, label };
  return {
    proposal: {
      id: "",
      kind: "create_bonus",
      summary: `Add bonus ${fmtMoney(amount, currency)} · ${monthYearLabel(year, month)}`,
      bonus: { currency, after: fields },
    },
    modelResult:
      "An add-bonus card is on screen — nothing is saved yet. Ask the user to review & Confirm.",
  };
}

async function proposeUpdateBonus(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const id = toNum(input.id);
  if (id == null || !Number.isInteger(id)) {
    return { error: "pass the numeric id of the bonus (from find_bonuses)" };
  }
  const row = await prisma.bonus.findFirst({ where: { id, userId } });
  if (!row) return { error: "no bonus with that id — call find_bonuses to get the id" };
  const currency = await userCurrency(userId);

  const before: BonusFields = { year: row.year, month: row.month, amount: Number(row.amount), label: row.label };
  const after: BonusFields = { ...before };
  let changed = false;
  if (input.amount !== undefined) {
    const a = toNum(input.amount);
    if (a == null || a <= 0) return { error: "amount must be a positive number" };
    after.amount = a;
    changed = true;
  }
  if (input.label !== undefined) {
    after.label = typeof input.label === "string" && input.label.trim() ? input.label.trim().slice(0, 40) : "Bonus";
    changed = true;
  }
  if (input.month !== undefined) {
    const m = toNum(input.month);
    if (m == null || m < 1 || m > 12) return { error: "month must be 1–12" };
    after.month = Math.round(m);
    changed = true;
  }
  if (input.year !== undefined) {
    const y = toNum(input.year);
    if (y == null) return { error: "year must be a number" };
    after.year = Math.round(y);
    changed = true;
  }
  if (!changed) return { error: "no changes given — say what to change (amount, label, month, year)" };

  const amountMoved = after.amount !== before.amount;
  return {
    proposal: {
      id: "",
      kind: "update_bonus",
      summary: amountMoved
        ? `Update bonus ${fmtMoney(before.amount, currency)} → ${fmtMoney(after.amount, currency)}`
        : `Update bonus · ${after.label}`,
      bonus: { currency, bonusId: row.id, before, after },
    },
    modelResult:
      "An edit-bonus card (before→after) is on screen — nothing is saved yet. Ask the user to review & Confirm.",
  };
}

async function proposeDeleteBonus(
  userId: string,
  input: ToolInput,
): Promise<WriteToolOutput | ToolError> {
  const id = toNum(input.id);
  if (id == null || !Number.isInteger(id)) {
    return { error: "pass the numeric id of the bonus (from find_bonuses)" };
  }
  const row = await prisma.bonus.findFirst({ where: { id, userId } });
  if (!row) return { error: "no bonus with that id — call find_bonuses to get the id" };
  const currency = await userCurrency(userId);
  const before: BonusFields = { year: row.year, month: row.month, amount: Number(row.amount), label: row.label };
  return {
    proposal: {
      id: "",
      kind: "delete_bonus",
      summary: `Delete bonus ${fmtMoney(before.amount, currency)} · ${before.label}`,
      bonus: { currency, bonusId: row.id, before },
    },
    modelResult:
      "A delete-bonus card is on screen — nothing is deleted yet. Ask the user to confirm.",
  };
}

/** Run one tool by name; the engine wraps this per tool_use block. */
export async function executeAssistantTool(
  userId: string,
  name: string,
  input: ToolInput,
  now: Date = new Date(),
): Promise<unknown> {
  switch (name) {
    case "find_expenses":
      return findExpenses(userId, input);
    case "find_recurring":
      return findRecurring(userId, input);
    case "get_financial_overview":
      return getFinancialOverview(userId, now);
    case "analyze_spending":
      return analyzeSpending(userId, input);
    case "project_savings":
      return projectSavings(userId, input, now);
    case "get_closed_months":
      return getClosedMonths(userId);
    case "get_preferences":
      return getPreferences(userId);
    case "find_bonuses":
      return findBonuses(userId, input);
    // WRITE tools (Slice 2) — return a proposal (no DB write); engine → confirm card.
    case "create_expense":
      return proposeCreateExpense(userId, input, now);
    case "update_expense":
      return proposeUpdateExpense(userId, input);
    case "delete_expense":
      return proposeDeleteExpense(userId, input);
    case "create_recurring":
      return proposeCreateRecurring(userId, input, now);
    case "edit_recurring":
      return proposeEditRecurring(userId, input, now);
    case "set_preference":
      return proposeSetPreference(input);
    case "set_month_status":
      return proposeSetMonthStatus(userId, input);
    // WRITE tools (Slice 2d — income management).
    case "set_savings_goal":
      return proposeSetSavingsGoal(userId, input);
    case "adjust_salary":
      return proposeAdjustSalary(userId, input, now);
    case "create_bonus":
      return proposeCreateBonus(userId, input, now);
    case "update_bonus":
      return proposeUpdateBonus(userId, input);
    case "delete_bonus":
      return proposeDeleteBonus(userId, input);
    default:
      return { error: `unknown tool: ${name}` };
  }
}
