// ADDED (AI Assistant · Slice 2): types shared by the server (tools/engine/actions)
// AND the client (AssistantChat confirm cards). Kept in a types-only module so the
// client can import them without pulling prisma (from tools.ts) into its bundle —
// type-only imports are erased at build time.
import type { CategoryKey, Currency } from "@/types";

/** The 7 writable spending categories (matches VALID_CATEGORIES in actions.ts and
 *  the tiles in VoiceEntryEditor — "family" is read-only, so writes never use it). */
export const WRITABLE_CATEGORIES: CategoryKey[] = [
  "food",
  "shop",
  "ent",
  "trans",
  "health",
  "bills",
  "other",
];

/** A complete, self-contained expense value — enough to render a card AND execute
 *  the write. `spentAt` is an ISO string (Date isn't serializable across the wire);
 *  null means "now" (create) / "leave as-is" (update). */
export interface ExpenseFields {
  amount: number;
  currency: Currency;
  category: CategoryKey;
  note: string;
  tags: string[];
  spentAt: string | null;
}

export type ProposalKind = "create_expense" | "update_expense" | "delete_expense";

/**
 * A WRITE the agent wants to make. The write tools NEVER touch the DB — they return
 * one of these, the engine surfaces it to the chat as a confirm card, and nothing is
 * saved until the user taps Confirm (→ executeAssistantAction). Self-contained so a
 * reload of the live turn's React state can still render/execute it.
 */
export interface Proposal {
  /** Stable id for keying + resolving on the client (the tool_use block id). */
  id: string;
  kind: ProposalKind;
  /** One-line human summary for the card header (e.g. "Add $12.00 · Food"). */
  summary: string;
  /** "YYYY-MM" if the affected month is hard-closed — the card warns / offers override. */
  closedMonth?: string | null;
  /** The row being changed is generated by a recurring rule — editing/deleting it
   *  touches only this month and leaves the rule out of sync (Slice 2b handles rules). */
  recurringWarning?: boolean;

  // create_expense
  create?: ExpenseFields;

  // update_expense
  expenseId?: number;
  before?: ExpenseFields;
  after?: ExpenseFields;

  // delete_expense
  target?: ExpenseFields;
}

/** What the client sends back to executeAssistantAction on Confirm (or after a
 *  manual edit in the VoiceEntryEditor). `fields` carries the FINAL values. */
export type AssistantActionInput =
  | { kind: "create_expense"; fields: ExpenseFields; overrideClosed?: boolean }
  | { kind: "update_expense"; expenseId: number; fields: ExpenseFields; overrideClosed?: boolean }
  | { kind: "delete_expense"; expenseId: number };

export interface AssistantActionResult {
  ok: boolean;
  /** Short confirmation for the resolved card, e.g. "Added $12.00 · Food". */
  summary?: string;
  error?: string;
}
