-- AlterTable
ALTER TABLE "User" ADD COLUMN     "deductions" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "grossSalary" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyBudget" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "payDay" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "payFrequency" TEXT NOT NULL DEFAULT 'Monthly';
